version: "2"
services:
  bd:
    build: ./psql
    cap_add:
      - net_bind_service
      - chown
      - fowner
      - setuid
      - setgid
      - dac_override
    cap_drop:
      - fsetid
      - kill
      - setpcap
      - net_raw
      - sys_chroot
      - mknod
      - audit_write
      - setfcap
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123
  rsyslog:
    build: ../instalação/docker/rsyslog
    cap_add:
      - net_bind_service
    cap_drop:
      - chown
      - dac_override
      - fowner
      - fsetid
      - kill
      - setgid
      - setuid
      - setpcap
      - net_raw
      - sys_chroot
      - mknod
      - audit_write
      - setfcap
    volumes:
      - ./logs:/var/log/
  restaf:
    build: ../instalação/docker/restaf
    ports: ["80"]
    cap_add:
      - net_bind_service
    cap_drop:
      - chown
      - dac_override
      - fowner
      - fsetid
      - kill
      - setgid
      - setuid
      - setpcap
      - net_raw
      - sys_chroot
      - mknod
      - audit_write
      - setfcap
    environment:
      - AF_SERVIDOR_ENDERECO=0.0.0.0:80
      - AF_SYSLOG_ENDERECO=rsyslog:514
      - AF_BD_ENDERECO=bd
      - AF_BD_SENHA=abc123
      - AF_ATIRADOR_CHAVE_CODIGO_VERIFICACAO=abc123
    depends_on:
      - "bd"
      - "rsyslog"
    links:
      - "bd:bd"
      - "rsyslog:rsyslog"